### ISSUE TITLE
Wrong counting the vowels

### ISSUE THREAD

**Issue by charandeep7** [Dishant145/text-input-counter#2]
'Catisananimal' has 6 vowels and 7 consonants. And It's showing 13 characters in total and (6 vowels+6 consonant) even though I didn't gave any spaces.
![WrongOutput](https://user-images.githubusercontent.com/96859500/195861312-580c9082-7568-4150-bc89-18e46d19e0dd.jpg)

**Comment by Dishant145** [comment]
Thanks for identifying this. Appreciate it a lot:)

**Comment by charandeep7** [comment]
please assign this issue to me. I'll solve it asap

**Comment by Dishant145** [comment]
I am sorry but I rectified it already.
